---
state: present

kube_system_namespace: kube-system
broker_namespace: openshift-template-service-broker
broker_image: docker.io/openshift/origin/template-service-broker:latest
broker_log_level: '0'
broker_node_selector: "{{ {'node-role.kubernetes.io/master':'true'} | to_json }}"
apiserver_service_name: apiserver

template_namespaces: ['openshift']

#__tsb_template_file: "apiserver-template.yaml"
#__tsb_config_file: "apiserver-config.yaml"
#__tsb_rbac_file: "rbac-template.yaml"
#__tsb_broker_file: "template-service-broker-registration.yaml"

#template_service_broker_image: "{{ l_os_registry_url | regex_replace('${component}' | regex_escape, 'template-service-broker') }}"
