updates:
  - file: "{MAJOR}.{MINOR}/openshifttemplateservicebrokeroperator.v{MAJOR}.{MINOR}.0.clusterserviceversion.yaml" # relative to this file
    update_list:
    # replace metadata.name value
    - search: "openshifttemplateservicebrokeroperator.v{MAJOR}.{MINOR}.0"
      replace: "openshifttemplateservicebrokeroperator.{FULL_VER}"
    # replace entire version line, otherwise would replace 4.1.0 anywhere
    - search: "version: {MAJOR}.{MINOR}.0"
      replace: "version: {FULL_VER}"
    - search: 'olm.skipRange: ">=4.1.0 <{MAJOR}.{MINOR}.0"'
      replace: 'olm.skipRange: ">=4.1.0 <{FULL_VER}"'
  - file: "openshifttemplateservicebroker.package.yaml"
    update_list:
    - search: "currentCSV: openshifttemplateservicebrokeroperator.v{MAJOR}.{MINOR}.0"
      replace: "currentCSV: openshifttemplateservicebrokeroperator.{FULL_VER}"
