---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-service-broker-operator
  namespace: openshift-template-service-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: template-service-broker-operator
  template:
    metadata:
      labels:
        name: template-service-broker-operator
    spec:
      serviceAccountName: template-service-broker-operator
      containers:
        - name: template-service-broker-operator
          image: REPLACE_IMAGE
          ports:
            - containerPort: 60000
              name: metrics
          imagePullPolicy: Always
          env:
            - name: IMAGE
              value: docker.io/openshift/origin-template-service-broker:latest
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "template-service-broker-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
