---
- name: Set apiserver_config if not already defined
  when: apiserver_config is not defined
  set_fact:
    apiserver_config: "{{ lookup('template', 'templateservicebrokerconfig.yaml') | to_json }}"

- name: Get available cluster APIs
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups', kubeconfig=lookup('env', 'K8S_AUTH_KUBECONFIG')) }}"

- name: "Set tsb objects state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: apiserver.serviceaccount.yaml
    - name: apiserver.clusterrole.yaml
    - name: apiserver.clusterrolebinding.yaml
    - name: apiserver.deployment.yaml
    - name: apiserver.configmap.yaml
    - name: apiserver.service.yaml
    - name: apiserver-service-ca-bundle.configmap.yaml
    - name: tsb-client.serviceaccount.yaml
    - name: tsb-client.clusterrole.yaml
    - name: tsb-client.clusterrolebinding.yaml
    - name: tsb-client.secret.yaml
    - name: tsb-operator.service-monitor.yaml
    - name: tsb-operator.monitor-role.yaml
    - name: tsb-operator.monitor-rolebinding.yaml
    - name: tsb.prometheus-alert.yaml

- name: "Set tsb config map state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'apiserver.configmap.yaml') | from_yaml }}"
  notify: Redeploy tsb if the configmap changed

- name: "Set clusterservicebroker state={{ state }}"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'apiserver.clusterservicebroker.yaml') | from_yaml }}"
